id: kattenburg-atlas
slug: kattenburg-atlas
title: Kattenburg Atlas
description: Een maritiem-militaire microkosmos
main: introductie

slideshows:
  - id: introductie
    path: slideshows/00-introductie
    title: Kattenburg Atlas

  - id: voor-1650
    path: slideshows/01-voor-1650
    title: Drooglegging
    description: |
      Het hele gebied is nog water, er worden kunstmatige eilanden gebouwd.

  - id: 1700-1800
    path: slideshows/02-1700-1800
    title: Vestiging, bloei en neergang
    description: |
      17e-18e eeuw: de periode van vestiging, bloei en neergang van de werf. In 1700 is het Marineterrein 50 jaar in gebruik. het eiland Kattenburg is uitgegroeid tot een wijk van scheepswerven en woonhuizen. Het marineterrein, 's Lands Werf genoemd, is inmiddels uitgebreid over de gehele lengte van Kattenburg en staat vol met werkplaatsen en magazijnen. De scheepstimmerlieden vormen een hechtte groep en stromen dagelijks met honderden anderen ambachtslieden en arbeiders de werf op. 

  - id: 1800-1900
    path: slideshows/03-1800-1900
    title: Malaise, nieuwe bloei en innovatie
    description: |
      19e eeuw: een periode met na malaise nieuwe bloei en innovatie: overgang naar stoom later en stookolie; ijkjaar is 1890, het monumentale Paleis, dat het terrein een volstrekt andere aanblik gaf, is net verrezen. Het personeel van de werf is intussen ontvankelijk voor socialistische sentimenten, er wordt actie gevoerd voor betere arbeidsomstandigheden.

  - id: 1940-1945
    path: slideshows/04-1940-1945
    title: Oorlog, bezetting, nasleep
    description: |
      Oorlog, bezetting, nasleep (1940-1946): Amsterdam komt in een donkere periode van angst en onzekerheid terecht. Kattenburg diende tijdens de bezetting als een van de steunpunten in de stad voor de Duitse intendance. De bezetter maakt van het Marineterrein een geheimzinnige plek. Terwijl de omliggende stad te maken krijgt met de wreedheden van de Nazi's en de oorlog blijft het een raadsel wat er zich achter de muren van het marineterrein afspeelt.

  - id: 1970-2000
    path: slideshows/05-1970-2000
    title: Kattenburg als militair-facilitair bedrijf
    description: |
       (1915-heden) Kattenburg als militair-facilitair bedrijf: Na het verdwijnen van de Rijkswerf uit Kattenburg neemt de bedrijfigheid en werkgelegenheid af. Als gevolg hiervan verkrotte en verpauperde de wijk Kattenburg ernorm. Als onderdeel van de Wederopbouwplannen van Amsterdam, werd ook Kattenburg gesloopt en vernieuwd. Met nieuwbouw, gallerijflats en veel groen is het karakter van de wijk sterk veranderd. Het Marineterrein maakte ook veel veranderingen mee en nam allerlei nieuwe vormen aan. De marine-inlichtingendienst vestigde zich, er verees een congresscentrum en opleidingscentra. En tot 1940 vestigden er zelf enkele civiele bedrijfjes. 
