id: kattenburg-atlas
slug: ""
title: Kattenburg Atlas
description: Een maritiem-militaire microkosmos
main: introductie

slideshows:
  - id: introductie
    path: slideshows/00-introductie
    title: Kattenburg Atlas

  - id: voor-1650
    path: slideshows/01-voor-1650
    title: Drooglegging

  - id: 1700-1800
    path: slideshows/02-1700-1800
    title: Vestiging, bloei en neergang

  - id: 1800-1900
    path: slideshows/03-1800-1900
    title: Malaise, nieuwe bloei en innovatie

  - id: 1940-1945
    path: slideshows/04-1940-1945
    title: Oorlog, bezetting, nasleep

  - id: 1970-2000
    path: slideshows/05-1970-2000
    title: Kattenburg als militair-facilitair bedrijf